name: bmad-godot-nakama-gamedev
version: 1.0.0
short-title: Godot + Nakama multiplayer game development
description: >-
  Comprehensive AI agent team for developing multiplayer games with Godot engine 
  and Nakama game server, specializing in brownfield integration and client-server architecture
author: BMAD Community 